# Generated by Django 4.0 on 2023-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('mobile', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('expirence', models.IntegerField()),
                ('position', models.CharField(max_length=64)),
            ],
        ),
    ]
